## Phase 1

1.Import Pandas and load the Online Retail Excel dataset into a DataFrame named df.
2.Display the first 5 transaction records and identify what each row represents.
3.Display the last 10 records and inspect whether the final transactions look structurally consistent.
4.Display 15 randomly selected transaction records to understand the variety of data.
5.Print the total number of rows and columns in the dataset.
6.Display all column names and identify the columns needed to analyze revenue.
7.Display the data type of every column and identify any unsuitable data types.
8.Determine how many rows and columns the original dataset contains.
9.Display the first 20 product descriptions and identify examples of different products.
10.Write a short business summary explaining what the dataset contains and what the company wants to learn.

## 1. Import Pandas and load the Online Retail Excel dataset into a DataFrame named df.

In [2]:
import pandas as pd

data = pd.read_csv("online_retail_practice_sample.csv")
print(data)
print("..........................................")
df=pd.DataFrame(data)
df

     InvoiceNo StockCode                          Description  Quantity  \
0      C536365     22423                                  NaN        -1
1       536365     22423             REGENCY CAKESTAND 3 TIER         7
2       536365     71053                  WHITE METAL LANTERN        10
3       536366    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         9
4       536366     22632            HAND WARMER RED POLKA DOT        14
...        ...       ...                                  ...       ...
1198    536764     22423             REGENCY CAKESTAND 3 TIER         3
1199    536764     23245           SET OF 3 REGENCY CAKE TINS         5
1200    536366    84406B       CREAM CUPID HEARTS COAT HANGER         5
1201    536371     22633               HAND WARMER UNION JACK         9
1202    536380      POST                              POSTAGE         9

              InvoiceDate  UnitPrice  CustomerID         Country
0     2011-01-27 09:13:00       0.00     12350.0         Germany
1     2011-09-06 10:03:00      12.75     12347.0  United Kingdom
2     2011-03-22 11:58:00       3.39     12347.0           Spain
3     2011-12-02 19:10:00       3.39     12356.0         Germany
4     2011-09-28 13:17:00       2.10     12347.0         Belgium
...                   ...        ...         ...             ...
1198  2011-07-14 20:06:00      12.75     12350.0           Spain
1199  2011-05-26 09:07:00       4.95     12348.0  United Kingdom
1200  2011-11-23 14:47:00       2.75     12349.0         Germany
1201  2011-02-10 12:13:00       2.10         NaN          France
1202  2011-01-20 09:07:00      18.00     12347.0  United Kingdom

[1203 rows x 8 columns]
..........................................

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,C536365,22423,NaN,-1,2011-01-27 09:13:00,0.00,12350.0,Germany
1,536365,22423,REGENCY CAKESTAND 3 TIER,7,2011-09-06 10:03:00,12.75,12347.0,United Kingdom
2,536365,71053,WHITE METAL LANTERN,10,2011-03-22 11:58:00,3.39,12347.0,Spain
3,536366,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,9,2011-12-02 19:10:00,3.39,12356.0,Germany
4,536366,22632,HAND WARMER RED POLKA DOT,14,2011-09-28 13:17:00,2.10,12347.0,Belgium
...,...,...,...,...,...,...,...,...
1198,536764,22423,REGENCY CAKESTAND 3 TIER,3,2011-07-14 20:06:00,12.75,12350.0,Spain
1199,536764,23245,SET OF 3 REGENCY CAKE TINS,5,2011-05-26 09:07:00,4.95,12348.0,United Kingdom
1200,536366,84406B,CREAM CUPID HEARTS COAT HANGER,5,2011-11-23 14:47:00,2.75,12349.0,Germany
1201,536371,22633,HAND WARMER UNION JACK,9,2011-02-10 12:13:00,2.10,NaN,France
1202,536380,POST,POSTAGE,9,2011-01-20 09:07:00,18.00,12347.0,United Kingdom

## 2.Display the first 5 transaction records and identify what each row represents.

In [3]:

df.head(5)
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,C536365,22423,NaN,-1,2011-01-27 09:13:00,0.00,12350.0,Germany
1,536365,22423,REGENCY CAKESTAND 3 TIER,7,2011-09-06 10:03:00,12.75,12347.0,United Kingdom
2,536365,71053,WHITE METAL LANTERN,10,2011-03-22 11:58:00,3.39,12347.0,Spain
3,536366,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,9,2011-12-02 19:10:00,3.39,12356.0,Germany
4,536366,22632,HAND WARMER RED POLKA DOT,14,2011-09-28 13:17:00,2.10,12347.0,Belgium
...,...,...,...,...,...,...,...,...
1198,536764,22423,REGENCY CAKESTAND 3 TIER,3,2011-07-14 20:06:00,12.75,12350.0,Spain
1199,536764,23245,SET OF 3 REGENCY CAKE TINS,5,2011-05-26 09:07:00,4.95,12348.0,United Kingdom
1200,536366,84406B,CREAM CUPID HEARTS COAT HANGER,5,2011-11-23 14:47:00,2.75,12349.0,Germany
1201,536371,22633,HAND WARMER UNION JACK,9,2011-02-10 12:13:00,2.10,NaN,France
1202,536380,POST,POSTAGE,9,2011-01-20 09:07:00,18.00,12347.0,United Kingdom

## 3.Display the last 10 records and inspect whether the final transactions look structurally consistent.

In [4]:

df.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1193,536762,84406B,CREAM CUPID HEARTS COAT HANGER,14,2011-10-12 12:43:00,2.75,12352.0,United Kingdom
1194,536763,23245,SET OF 3 REGENCY CAKE TINS,15,2011-01-27 17:37:00,4.95,12349.0,Netherlands
1195,536763,22632,HAND WARMER RED POLKA DOT,5,2011-06-08 20:37:00,2.10,12350.0,EIRE
1196,536763,84406B,CREAM CUPID HEARTS COAT HANGER,2,2011-08-28 08:47:00,2.75,12349.0,Spain
1197,536764,84406B,CREAM CUPID HEARTS COAT HANGER,13,2011-08-11 20:52:00,2.75,12356.0,Germany
1198,536764,22423,REGENCY CAKESTAND 3 TIER,3,2011-07-14 20:06:00,12.75,12350.0,Spain
1199,536764,23245,SET OF 3 REGENCY CAKE TINS,5,2011-05-26 09:07:00,4.95,12348.0,United Kingdom
1200,536366,84406B,CREAM CUPID HEARTS COAT HANGER,5,2011-11-23 14:47:00,2.75,12349.0,Germany
1201,536371,22633,HAND WARMER UNION JACK,9,2011-02-10 12:13:00,2.10,NaN,France
1202,536380,POST,POSTAGE,9,2011-01-20 09:07:00,18.00,12347.0,United Kingdom

## 4.Display 15 randomly selected transaction records to understand the variety of data.

In [5]:

df.sample(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
62,536385,71053,WHITE METAL LANTERN,3,2011-01-24 20:01:00,3.39,12352.0,France
856,536650,84406B,CREAM CUPID HEARTS COAT HANGER,14,2011-10-27 17:31:00,2.75,12352.0,Belgium
1058,536717,POST,POSTAGE,9,2011-01-15 10:38:00,18.00,NaN,Spain
671,536588,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,10,2011-01-19 08:51:00,3.39,NaN,Belgium
463,536519,84406B,CREAM CUPID HEARTS COAT HANGER,7,2011-03-11 13:40:00,2.75,12350.0,EIRE
1168,536754,23245,SET OF 3 REGENCY CAKE TINS,1,2011-05-26 10:03:00,4.95,NaN,EIRE
391,536495,POST,POSTAGE,9,2011-05-16 18:56:00,18.00,12356.0,France
1121,536738,22752,SET 7 BABUSHKA NESTING BOXES,1,2011-12-06 18:05:00,8.50,12349.0,Germany
208,536434,22752,SET 7 BABUSHKA NESTING BOXES,13,2011-02-28 11:34:00,8.50,NaN,France
775,536623,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,9,2011-05-19 12:29:00,3.39,12350.0,Spain
1063,536719,85123A,WHITE HANGING HEART T-LIGHT HOLDER,3,2011-09-11 12:40:00,2.55,12354.0,EIRE
643,536579,POST,POSTAGE,10,2010-12-29 20:40:00,18.00,12356.0,France
888,536661,22632,HAND WARMER RED POLKA DOT,10,2011-11-03 11:23:00,2.10,NaN,Belgium
902,536665,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2011-08-18 15:16:00,3.39,NaN,Spain
180,536425,22386,JUMBO BAG PINK POLKADOT,14,2011-09-23 18:57:00,1.95,12349.0,EIRE

## 5. Print the total number of rows and columns

In [6]:

print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Total rows: 1203
Total columns: 8

## 6. Display all column names and identify columns needed to analyze revenue

In [7]:

print(df.columns)

print("Columns needed for revenue analysis:")
print(["Quantity", "UnitPrice"])

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')
Columns needed for revenue analysis:
['Quantity', 'UnitPrice']

## 7. Display the data type of every column

In [8]:

df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

## 8. Determine the number of rows and columns in the original dataset

In [9]:

print("Original rows:", df.shape[0])
print("Original columns:", df.shape[1])

Original rows: 1203
Original columns: 8

## 9. Display the first 20 product descriptions

In [10]:
df["Description"].head(20)

0                                     NaN
1                REGENCY CAKESTAND 3 TIER
2                     WHITE METAL LANTERN
3     KNITTED UNION FLAG HOT WATER BOTTLE
4               HAND WARMER RED POLKA DOT
5          CREAM CUPID HEARTS COAT HANGER
6                HOME BUILDING BLOCK WORD
7                HOME BUILDING BLOCK WORD
8                     WHITE METAL LANTERN
9     KNITTED UNION FLAG HOT WATER BOTTLE
10                 HAND WARMER UNION JACK
11              HAND WARMER RED POLKA DOT
12               REGENCY CAKESTAND 3 TIER
13               REGENCY CAKESTAND 3 TIER
14           SET 7 BABUSHKA NESTING BOXES
15               HOME BUILDING BLOCK WORD
16                 HAND WARMER UNION JACK
17               REGENCY CAKESTAND 3 TIER
18                 HAND WARMER UNION JACK
19             SET OF 3 REGENCY CAKE TINS
Name: Description, dtype: str

In [11]:

print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [12]:

print(df["Description"].head(20))

0                                     NaN
1                REGENCY CAKESTAND 3 TIER
2                     WHITE METAL LANTERN
3     KNITTED UNION FLAG HOT WATER BOTTLE
4               HAND WARMER RED POLKA DOT
5          CREAM CUPID HEARTS COAT HANGER
6                HOME BUILDING BLOCK WORD
7                HOME BUILDING BLOCK WORD
8                     WHITE METAL LANTERN
9     KNITTED UNION FLAG HOT WATER BOTTLE
10                 HAND WARMER UNION JACK
11              HAND WARMER RED POLKA DOT
12               REGENCY CAKESTAND 3 TIER
13               REGENCY CAKESTAND 3 TIER
14           SET 7 BABUSHKA NESTING BOXES
15               HOME BUILDING BLOCK WORD
16                 HAND WARMER UNION JACK
17               REGENCY CAKESTAND 3 TIER
18                 HAND WARMER UNION JACK
19             SET OF 3 REGENCY CAKE TINS
Name: Description, dtype: str

In [13]:



import pandas as pd

df = pd.read_excel("Online_Retail_Practice.xlsx")

print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    570338     71053                  WHITE METAL LANTERN         7
1    574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
2    545052    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         0
3    567005     71053                  WHITE METAL LANTERN        12
4    573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15

          InvoiceDate  UnitPrice  CustomerID      Country
0 2011-09-15 15:26:00       4.07     16640.0       Sweden
1 2011-06-05 08:10:00       4.25     17154.0       Sweden
2 2011-07-24 03:45:00       3.39     16783.0  Netherlands
3 2011-09-04 16:55:00       3.39     14222.0        Spain
4 2011-02-23 13:40:00       3.39     16830.0       Sweden

In [15]:

df.to_excel("My_Excel_File.xlsx", index=False)

print("Excel file saved successfully!")

Excel file saved successfully!